# Generated by Django 4.0.1 on 2022-07-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
